# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
  armhf: "ghcr.io/home-assistant/armhf-base:latest"
  armv7: "ghcr.io/home-assistant/armv7-base:latest"
  i386: "ghcr.io/home-assistant/i386-base:latest"
labels:
  org.opencontainers.image.title: "Traefik addon"
  org.opencontainers.image.description: "Traefik add-on"
  org.opencontainers.image.source: "https://github.com/nyok92/hassio-addons/traefik"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
#  TRAEFIK_VERSION: 2.11.0
  TRAEFIK_VERSION: 3.1.2
