# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
labels:
  org.opencontainers.image.title: "Traefik addon"
  org.opencontainers.image.description: "Traefik add-on"
  org.opencontainers.image.source: "https://github.com/nyok92/hassio-addons/traefik"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TRAEFIK_VERSION: 3.6.7
